---
scp_font_url: 'https://github.com/adobe-fonts/source-code-pro/archive/2.010R-ro/1.030R-it.zip'
scp_font_file: 'source-code-pro-2.010R-ro-1.030R-it'

hasklig_font_file: 'Hasklig-1.1'
hasklig_font_url: 'https://github.com/i-tu/Hasklig/releases/download/1.1/{{ hasklig_font_file }}.zip'
