---

- name: Install base packages
  become: yes
  become_method: sudo
  apt:
    name: ['tmux', 'htop', 'zsh', 'socat', 'keychain', 'curl', 'build-essential', 'openssh-server']
    state: latest

- name: Install docker apt dependencies
  become: yes
  become_method: sudo
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'software-properties-common']
    state: latest

- name: Install docker repository [18.04]
  apt_repository:
    repo: https://download.docker.com/linux/ubuntu bionic stable
    state: present
  when: ansible_distribution_version == "18.04"

- name: Install docker repository [16.04]
  apt_repository:
    repo: https://download.docker.com/linux/ubuntu xenial stable
    state: present
  when: ansible_distribution_version == "16.04"

- name: Install docker
  apt:
    update_cache: yes
    name: ['docker-ce']
    state: latest

