---

- name: Check if Kraken cooler exists
  shell: "lsusb | grep {{ kraken_usb_version }} | awk '{print $6}'"
  ignore_errors: true
  register: kraken_usb

- name: Check if Service Exists
  stat: path=/etc/systemd/system/levd.service
  register: service_status

- include: kraken.yml
  when: (kraken_usb.stdout == "2433:b200") and (service_status.stat.exists == false)
