---

- name: Install emacs dependencies [ubuntu]
  become: yes
  become_method: sudo
  apt:
    name: ['libc6-dev', 'libjpeg62-dev', 'libncurses5-dev', 'libpng-dev', 'xaw3dg-dev', 'zlib1g-dev', 'libice-dev', 'libsm-dev', 'libx11-dev', 'libxext-dev', 'libxi-dev', 'libxmu-dev', 'libxmuu-dev', 'libxpm-dev', 'libxrandr-dev', 'libxt-dev', 'libxtst-dev', 'libxv-dev', 'libgif-dev', 'pkg-config', 'libxft2-dev']
    state: latest
  when: ansible_os_family == 'Debian'

- name: Install emacs dependencies [fedora]
  become: yes
  become_method: sudo
  dnf:
    name: ['glibc-devel', 'libjpeg-turbo-devel', 'ncurses-devel', 'libpng-devel', 'libtiff-devel', 'giflib-devel', 'Xaw3d-devel', 'zlib-devel', 'libSM-devel', 'libX11-devel', 'libXext-devel', 'libXi-devel', 'libXmu-devel', 'libXpm-devel', 'libXrandr-devel', 'libXt-devel', 'libXtst-devel', 'libXv-devel', 'ccls', 'gnutls-devel', 'libXft-devel']
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Download emacs '{{ emacs_version }}'
  get_url:
    url: http://reflection.oss.ou.edu/gnu/emacs/emacs-{{ emacs_version }}.tar.gz
    dest: '{{ reborn_cache_dir }}'

- name: Unarchive emacs
  unarchive:
    remote_src=yes
    src='{{ reborn_cache_dir }}/emacs-{{ emacs_version }}.tar.gz'
    dest='{{ reborn_cache_dir }}'
    creates='{{ reborn_cache_dir }}/emacs-{{ emacs_version }}'
  register: unarchive

- name: Configure emacs
  shell: ./configure
  args:
    chdir: '{{ reborn_cache_dir }}/emacs-{{ emacs_version }}'

- name: Build & Install emacs
  become: yes
  become_method: sudo
  shell: make -j{{ ansible_processor_vcpus }} install
  args:
    chdir: '{{ reborn_cache_dir }}/emacs-{{ emacs_version }}'

- name: Install spacemacs
  git:
    repo: 'https://github.com/syl20bnr/spacemacs'
    dest: ~/.emacs.d
    force: yes
    version: develop

- name: Copy my personal spacemacs config into ~/.spacemacs
  copy:
    force=yes
    src=spacemacs
    dest=~/.spacemacs
